# Generated by Django 4.2.5 on 2023-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwebsite',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
