# Generated by Django 4.2.5 on 2023-12-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_userwebsite_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterField(
            model_name='userwebsite',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
