# Generated by Django 4.2.5 on 2023-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_website_alter_userwebsite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwebsite',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
